<?php

declare(strict_types=1);

namespace Acme\Widget\Databases;

use Acme\Widget\Domain\Database;

/**
 * Default catalogue and charge rules from the Acme Widget Co brief.
 *
 * Safe to run more than once: products and charge rules are upserted by
 * code, so existing records are updated rather than duplicated. Ids are
 * generated by the database.
 */
final class Seed
{
    private const PRODUCTS = [
        ['code' => 'R01', 'name' => 'Red Widget', 'price' => 3295],
        ['code' => 'G01', 'name' => 'Green Widget', 'price' => 2495],
        ['code' => 'B01', 'name' => 'Blue Widget', 'price' => 795],
    ];

    private const CHARGE_RULES = [
        [
            'code' => 'red_widget_second_half_price',
            'rule' => 'product_discount_by_quantity',
            'data' => [
                'product_code' => 'R01',
                'full_quantity' => 1,
                'discount_quantity' => 1,
                'discount_percent' => 50,
            ],
            'precedence' => 0,
            'label' => 'offer',
            'name' => 'Buy one red widget, get the second half price',
        ],
        [
            'code' => 'delivery_free_fallback',
            'rule' => 'delivery_price_by_subtotal',
            'data' => ['min_subtotal' => null, 'max_subtotal' => null, 'charge' => 0],
            'precedence' => 100,
            'label' => 'policy',
            'name' => 'Free delivery fallback',
        ],
        [
            'code' => 'delivery_under_90',
            'rule' => 'delivery_price_by_subtotal',
            'data' => ['min_subtotal' => null, 'max_subtotal' => 9000, 'charge' => 295],
            'precedence' => 110,
            'label' => 'policy',
            'name' => 'Delivery under $90',
        ],
        [
            'code' => 'delivery_under_50',
            'rule' => 'delivery_price_by_subtotal',
            'data' => ['min_subtotal' => null, 'max_subtotal' => 5000, 'charge' => 495],
            'precedence' => 120,
            'label' => 'policy',
            'name' => 'Delivery under $50',
        ],
    ];

    public static function run(Database $database): void
    {
        foreach (self::PRODUCTS as $product) {
            $database->upsertProduct(...$product);
        }

        foreach (self::CHARGE_RULES as $rule) {
            $database->upsertChargeRule(...$rule);
        }
    }
}
